spring.application.name=SBDemo
server.port = 8081
#server.servlet.context-path=/myapp
trainer.name=Kaushik
trainer.course=SpringBoot
server.error.include-message=always
server.error.include-binding-errors=always