spring.application.name=ApiGatewayApp1
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.server.webflux.routes[0].id=UserServiceApp
spring.cloud.gateway.server.webflux.routes[0].uri=lb://UserServiceApp
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/user/**

spring.cloud.gateway.server.webflux.routes[1].id=OrderServiceApp
spring.cloud.gateway.server.webflux.routes[1].uri=lb://OrderServiceApp
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/order/**


spring.config.import=optional:configserver:http://localhost:8888