spring.application.name=SBSecurityDemo
#spring.security.user.name=admin
#spring.security.user.password=123


spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory1
spring.datasource.username=root
spring.datasource.password=root
